Version: 1.0

Chance to get this enchant in the table: 5.0
Enabled blocks:
  - 'STONE'
  - 'SANDSTONE'
  - 'RED_SANDSTONE'
  - 'COBBLESTONE'
  - 'GRANITE'
  - 'DIORITE'
  - 'ANDESITE'
  - 'CALCITE'
  - 'OBSIDIAN'
  - 'IRON_ORE'
  - 'COAL_ORE'
  - 'GOLD_ORE'
  - 'LAPIS_ORE'
  - 'DIAMOND_ORE'
  - 'EMERALD_ORE'
  - 'NETHER_QUARTZ_ORE'
  - 'NETHER_GOLD_ORE'
  - 'COPPER_ORE'
  - 'GLOWSTONE'
  - 'ANCIENT_DEBRIS'
  - 'TUFF'
  - 'STONE_BRICKS'
  - 'MOSSY_STONE_BRICKS'
  - 'CRACKED_STONE_BRICKS'
  - 'CHISELED_STONE_BRICKS'
  - 'END_STONE_BRICKS'
  - 'END_STONE'
  - 'PRISMARINE_BRICKS'
  - 'POLISHED_BLACKSTONE_BRICKS'
  - 'CRACKED_POLISHED_BLACKSTONE_BRICKS'
  - 'GILDED_BLACKSTONE'
  - 'CHISELED_POLISHED_BLACKSTONE'
  - 'DEEPSLATE_TILES'
  - 'CRACKED_DEEPSLATE_TILES'
  - 'DEEPSLATE_BRICKS'
  - 'CRACKED_DEEPSLATE_BRICKS'
  - 'NETHERRACK'
  - 'MAGMA_BLOCK'
  - 'BLACKSTONE'
  - 'DEEPSLATE'
  - 'POLISHED_DIORITE'
  - 'POLISHED_ANDESITE'
  - 'POLISHED_BLACKSTONE'
  - 'POLISHED_DEEPSLATE'
  - 'REDSTONE_ORE'
  - 'DEEPSLATE_IRON_ORE'
  - 'DEEPSLATE_GOLD_ORE'
  - 'DEEPSLATE_DIAMOND_ORE'
  - 'DEEPSLATE_LAPIS_ORE'
  - 'DEEPSLATE_REDSTONE_ORE'
  - 'DEEPSLATE_EMERALD_ORE'
  - 'DEEPSLATE_COPPER_ORE'
  - 'DEEPSLATE_COAL_ORE'
  - 'AMETHYST_BLOCK'
  - 'BUDDING_AMETHYST'
  - 'POLISHED_GRANITE'
  - 'COAL_BLOCK'
  - 'REDSTONE_BLOCK'
  - 'LAPIS_BLOCK'
  - 'IRON_BLOCK'
  - 'DIAMOND_BLOCK'
  - 'EMERALD_BLOCK'
  - 'GOLD_BLOCK'


# MESSAGES

You can not the player: '&cYou are not the player!'
You dont have the permission: '&cYou dont have the permission!'
Enchanted message: '&fYou have enchanted a 3x3 loot item!'
Plugin reloaded: '&fPickaxe3x3 plugin reloaded!'
Its not a pickaxe in your main hand: '&cIts not a pickaxe in your main hand!'
Enchant message to lore:
  - '&73x3'